---
title: "bibliometric_analysis"
output: html_document
---


# Web of Science

Re-running the same search parameters returned 1397 results (a few more than originally provided).

Link to query: https://www.webofscience.com/wos/woscc/summary/09ad7c24-14b3-435b-9eab-a6e53518a168-0022b2f2/date-ascending/1

```{r WoS, echo=FALSE, results="show", message=FALSE}
library(bibliometrix)

wos_data <- convert2df(file = "data/webofscience_1-1397.txt", dbsource = 'wos',
                       format = 'plaintext')
wos_results <- biblioAnalysis(wos_data, sep = ";")

wos_summary <- summary(wos_results)

plot(wos_results)
print(wos_summary)


# CR <- citations(wos_data, field = "article", sep = ";")
# cbind(CR$Cited[1:10])

CR_local <- localCitations(wos_data, sep = ";")
CR_local$Authors[1:10,]
CR_local$Papers[1:10,]


```




# Scopus

Re-running search parameters for Scopus returned 1770 results.

link to query: https://www-scopus-com.ezproxy.auckland.ac.nz/results/results.uri?sort=plf-f&src=s&sid=e992393549b76fbc30119a8057500cdd&sot=a&sdt=a&sl=120&s=TITLE-ABS-KEY%28%22climate+justice%22+OR+%22environmental+justice%22+OR+%22social+justice%22+AND+%22climate+change%22+OR+%22Global+warming%22%29&origin=searchadvanced&editSaveSearch=&txGid=67869551553f160ede325131982356bc

```{r scopus, echo=FALSE, results="show", message=FALSE}
library(bibliometrix)
scopus_data <- convert2df(file = "data/scopus_1770.bib", dbsource = 'scopus',
                       format = 'bibtex')
scopus_results <- biblioAnalysis(scopus_data, sep = ";")

scopus_summary <- summary(scopus_results)

plot(scopus_results)
print(scopus_summary)


```
